<a href="https://colab.research.google.com/github/hikyle02/PolytechTest/blob/master/IntoThePython0629.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# 예제 데이터
features = [[1, 2], [3, 4], [5, 6]]
labels = [0, 1, 0]

# 튜플을 사용하여 데이터셋 생성
dataset = tf.data.Dataset.from_tensor_slices((features, labels))

for element in dataset:
    print(element)


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [ ]:
def calculate_statistics(numbers):
    mean = sum(numbers) / len(numbers)
    variance = sum((x - mean) ** 2 for x in numbers) / len(numbers)
    return mean, variance

# 튜플로 반환된 값을 함수 인수로 사용
numbers = [1, 2, 3, 4, 5]
mean, variance = calculate_statistics(numbers)
print(f"Mean: {mean}, Variance: {variance}")

def print_statistics(statistics):
    mean, variance = statistics
    print(f"Mean: {mean}, Variance: {variance}")

# 튜플을 인수로 전달
print_statistics((mean, variance))


Mean: 3.0, Variance: 2.0
Mean: 3.0, Variance: 2.0


In [ ]:
# 딕셔너리 생성
example_dict = {'name': 'Alice', 'age': 25, 'city': 'Seoul'}

# items() 메서드 사용
print("Items:")
for key, value in example_dict.items():
    print(f"Key: {key}, Value: {value}")

# keys() 메서드 사용
print("\nKeys:")
for key in example_dict.keys():
    print(f"Key: {key}")

# values() 메서드 사용
print("\nValues:")
for value in example_dict.values():
    print(f"Value: {value}")


Items:
Key: name, Value: Alice
Key: age, Value: 25
Key: city, Value: Seoul

Keys:
Key: name
Key: age
Key: city

Values:
Value: Alice
Value: 25
Value: Seoul


In [ ]:
# Mutable 예시 (리스트)
mutable_list = [1, 2, 3]
print("Original list:", mutable_list)
print("Original list id:", id(mutable_list))

mutable_list.append(4)
print("Modified list:", mutable_list)
print("Modified list id:", id(mutable_list))

# Immutable 예시 (튜플)
immutable_tuple = (1, 2, 3)
print("\nOriginal tuple:", immutable_tuple)
print("Original tuple id:", id(immutable_tuple))

try:
    immutable_tuple[0] = 4  # 이 부분에서 TypeError가 발생합니다
except TypeError as e:
    print("Error:", e)

# 새로운 튜플 생성
new_tuple = immutable_tuple + (4,)
print("New tuple:", new_tuple)
print("New tuple id:", id(new_tuple))

Original list: [1, 2, 3]
Original list id: 132593467427584
Modified list: [1, 2, 3, 4]
Modified list id: 132593467427584

Original tuple: (1, 2, 3)
Original tuple id: 132593467582528
Error: 'tuple' object does not support item assignment
New tuple: (1, 2, 3, 4)
New tuple id: 132595821557968


In [ ]:
# 리스트를 이용한 예시
my_list = [1, 2, 3, 4, 5]
for item in my_list:
    print(item, end=' ')
print()  # 출력: 1 2 3 4 5

# 문자열을 이용한 예시
my_string = "Hello"
for char in my_string:
    print(char, end=' ')
print()  # 출력: H e l l o

# range 객체를 이용한 예시
for num in range(5):
    print(num, end=' ')
print()  # 출력: 0 1 2 3 4

# 딕셔너리를 이용한 예시
my_dict = {"a": 1, "b": 2, "c": 3}
for key in my_dict:
    print(f"{key}: {my_dict[key]}", end=' ')
print()  # 출력: a: 1 b: 2 c: 3

# iterable 객체를 list()로 변환
print(list("Python"))  # 출력: ['P', 'y', 't', 'h', 'o', 'n']

# 사용자 정의 iterable 클래스 예시
class CountDown:
    def __init__(self, start):
        self.start = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.start <= 0:
            raise StopIteration
        self.start -= 1
        return self.start + 1

# 사용자 정의 iterable 사용
for num in CountDown(5):
    print(num, end=' ')
print()  # 출력: 5 4 3 2 1

1 2 3 4 5 
H e l l o 
0 1 2 3 4 
a: 1 b: 2 c: 3 
['P', 'y', 't', 'h', 'o', 'n']
5 4 3 2 1 


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# 가상의 데이터셋
data = np.array([[1, 2], [3, 4], [5, 6]])

# StandardScaler는 iterable을 입력으로 받습니다
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# 데이터 로드
iris = load_iris()
X, y = iris.data, iris.target

# KFold는 iterable을 반환합니다
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_index, val_index) in enumerate(kf.split(X), 1):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    model = LogisticRegression()
    model.fit(X_train, y_train)

    val_score = model.score(X_val, y_val)
    print(f"Fold {fold} validation score: {val_score:.4f}")


Fold 1 validation score: 1.0000
Fold 2 validation score: 1.0000


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Fold 3 validation score: 0.9333
Fold 4 validation score: 0.9667
Fold 5 validation score: 0.9667


In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# 데이터 로드 및 스케일링
iris = load_iris()
X, y = iris.data, iris.target
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# KFold 설정
# KFold는 iterable을 반환합니다
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_index, val_index) in enumerate(kf.split(X_scaled), 1):
    X_train, X_val = X_scaled[train_index], X_scaled[val_index]
    y_train, y_val = y[train_index], y[val_index]

    model = LogisticRegression(max_iter=1000, C=0.1)
    model.fit(X_train, y_train)

    val_score = model.score(X_val, y_val)
    print(f"Fold {fold} validation score: {val_score:.4f}")

Fold 1 validation score: 0.9667
Fold 2 validation score: 0.8667
Fold 3 validation score: 0.9333
Fold 4 validation score: 0.9000
Fold 5 validation score: 0.9333


In [ ]:
# 예시 데이터
data = ['cat', 'dog', 'bird', 'fish']

# enumerate()를 사용하여 인덱스와 데이터를 동시에 출력
for idx, value in enumerate(data):
    print(f"Index: {idx}, Value: {value}")


Index: 0, Value: cat
Index: 1, Value: dog
Index: 2, Value: bird
Index: 3, Value: fish


In [ ]:
# 가상의 학습 손실 값
losses = [0.9, 0.7, 0.5, 0.3]

# enumerate()를 사용하여 에포크와 손실 값을 출력
for epoch, loss in enumerate(losses):
    print(f"Epoch: {epoch}, Loss: {loss}")


Epoch: 0, Loss: 0.9
Epoch: 1, Loss: 0.7
Epoch: 2, Loss: 0.5
Epoch: 3, Loss: 0.3


In [ ]:
import re

pattern = r'(\w+) (\w+)'
text = "Hello World"

match = re.search(pattern, text)

if match:
  print(match.group(1)) # 출 력: Hello
  print(match.group(2)) # 출 력: World

Hello
World


In [ ]:
pattern = r'\d{3}-\d{3}-\d{4}'
text = "You can reach me at 123-456-7890 or 987-654-3210."
matches = re.findall(pattern, text)
print(matches) # 출 력: ['123-456-7890', '987-654-3210']

['123-456-7890', '987-654-3210']


In [ ]:
pattern = r'<.*?>'
text = "<p>This is a <b>bold</b> paragraph.</p>"
clean_text = re.sub(pattern, '', text)
print(clean_text) # 출 력: This is a bold paragraph.


This is a bold paragraph.


In [ ]:
import re

pattern_greedy = r'<.*>'
text = "<p>This is a <b>bold</b> paragraph.</p>"
clean_text_greedy = re.sub(pattern_greedy, '', text)
print(clean_text_greedy)  # 출력:



In [ ]:
import re

pattern_greedy = r'<.*>'
text = "<p>This is a <b>bold</b> paragraph.</p>"
clean_text_greedy = re.sub(pattern_greedy, '', text)
print(clean_text_greedy)  # 출력:


In [ ]:
import re

pattern_nongreedy = r'<.*?>'
text = "<p>This is a <b>bold</b> paragraph.</p>"
clean_text_nongreedy = re.sub(pattern_nongreedy, '', text)
print(clean_text_nongreedy)  # 출력: This is a bold paragraph.


This is a bold paragraph.


In [ ]:
pattern = r'^Hello'
text1 = "Hello World"
text2 = "Hi there"
match1 = re.match(pattern, text1)
match2 = re.match(pattern, text2)
print(match1) # 출 력: <re.Match object; span=(0, 5), match='Hello'>
print(match2) # 출 력: None

<re.Match object; span=(0, 5), match='Hello'>
None


In [ ]:
import re
pattern = r'\d+' # 숫 자 를 기 준 으 로 문 자 열 분 할
text = "Hello 123 World 456 Python 789"
splits = re.split(pattern, text)
print("Splits:", splits) # Splits: ['Hello ', ' World ', ' Python ', '']

Splits: ['Hello ', ' World ', ' Python ', '']


In [ ]:
import re
pattern = r'\d+' # 문 자 열 의 숫 자 를 'N'으 로 변 경
text = "Hello 123 World 456 Python 789"
new_text = re.sub(pattern, 'N', text)
print("New text:", new_text) # New text: Hello N World N Python N

New text: Hello N World N Python N


In [ ]:
import re
pattern = r'\d+' # 문 자 열 에 포 함 된 모 든 숫 자 찾 기
text = "Hello 123 World 456 Python 789"
matches = re.finditer(pattern, text)
for match in matches:
  print("Match found:", match.group())

Match found: 123
Match found: 456
Match found: 789


In [ ]:
import re
pattern = r'\d+' # 문 자 열 에 포 함 된 모 든 숫 자 찾 기
text = "Hello 123 World 456 Python 789"
matches = re.findall(pattern, text)
print("Matches:", matches) # Matches: ['123', '456', '789']

Matches: ['123', '456', '789']


In [ ]:
import re
pattern = r'\d+' # 문 자 열 에 숫 자 가 포 함 되 어 있 는 지 확 인
text = "Hello 123 World 456"
search = re.search(pattern, text)
if search:
  print("Match found:", search.group()) # Match found: 123
else:
  print("No match found")

Match found: 123


In [ ]:
import re
pattern = r'(\w+) (\w+)'
text = "Hello World"
match = re.match(pattern, text)
if match:
  print("Match found:", match.group()) # Match found: Hello World
  print("Groups:", match.groups()) # Groups: ('Hello', 'World')
  print("Start:", match.start()) # Start: 0
  print("End:", match.end()) # End: 11
  print("Span:", match.span()) # Span:(0, 11)
else:
  print("No match found")


Match found: Hello World
Groups: ('Hello', 'World')
Start: 0
End: 11
Span: (0, 11)


In [ ]:
enumerate()

In [ ]:
print()

In [ ]:
a=10
id(a)

137782988472848

In [ ]:
print(id(a))

137782988472848


In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [ ]:
if 0+0:
  print("true")
else:
  print("False")

False


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 데이터 생성
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

# 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


Accuracy: 1.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터 생성
X = np.random.rand(100, 10)
y = np.random.randint(2, size=100)

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 모델 생성
model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(1, activation='sigmoid')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train, epochs=10, batch_size=32)

# 모델 평가
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy}')


Epoch 1/10
3/3 [==============================] - 1s 9ms/step - loss: 0.7012 - accuracy: 0.5000
Epoch 2/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6923 - accuracy: 0.5500
Epoch 3/10
3/3 [==============================] - 0s 7ms/step - loss: 0.6893 - accuracy: 0.5500
Epoch 4/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6829 - accuracy: 0.5875
Epoch 5/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6803 - accuracy: 0.6125
Epoch 6/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6765 - accuracy: 0.5750
Epoch 7/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6750 - accuracy: 0.5625
Epoch 8/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6723 - accuracy: 0.5625
Epoch 9/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6711 - accuracy: 0.5625
Epoch 10/10
1/1 [==============================] - 0s 212ms/step - loss: 0.7304 - accuracy: 0.5000
Accuracy: 0.5


In [ ]:
a = 15/5

In [ ]:
type(a)

float

In [ ]:
b = 38//12
type(b)

int

In [ ]:
c=35/7.0

In [ ]:
type(c)

float

In [ ]:
d=3.8/1.2

print(d)

3.1666666666666665


In [ ]:
e=3.8%1.2

print(e)

0.19999999999999996


In [ ]:
# 불 리 언 값 입 력 받 기
bool1 = bool(input("첫 번 째 불 리 언 값 을 입 력 하 세 요: "))
# 입 력 받 은 값 이 비 어 있 으 면 False로 변 환 됨
bool2 = bool(input("두 번 째 불 리 언 값 을 입 력 하 세 요: "))
# AND 연 산 수 행 후 결 과 출 력
result = bool1 and bool2
print("AND 연 산 결 과:", result)

첫 번 째 불 리 언 값 을 입 력 하 세 요: 
두 번 째 불 리 언 값 을 입 력 하 세 요: 
AND 연 산 결 과: False


In [ ]:
# 세 숫 자 입 력 받 기
num1 = float(input("첫 번 째 숫 자 를 입 력 하 세 요: "))
num2 = float(input("두 번 째 숫 자 를 입 력 하 세 요: "))
num3 = float(input("세 번 째 숫 자 를 입 력 하 세 요: "))
# 가 장 큰 숫 자 비 교 후 출 력
max_num = max(num1, num2, num3)
print("가 장 큰 숫 자:", max_num)


첫 번 째 숫 자 를 입 력 하 세 요: 234
두 번 째 숫 자 를 입 력 하 세 요: 32
세 번 째 숫 자 를 입 력 하 세 요: 132
가 장 큰 숫 자: 234.0


In [ ]:
import numpy as np

# 데이터셋
data = np.array([100, 200, 300, 400, 500], dtype=float)  # 데이터 타입을 float로 설정

# 데이터 스케일링 (표준화)
mean = np.mean(data)
std = np.std(data)

data -= mean  # data = data - mean
data /= std   # data = data / std

print(data_standardized)



[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# 실제 값과 예측 값
actual = np.array([1.0, 2.0, 3.0])
predicted = np.array([1.1, 1.9, 3.2])

# MSE 계산
mse = np.mean((actual - predicted) ** 2)
print(mse)

0.020000000000000035


In [ ]:
# 가중치 초기화

weights = np.array([0.5, -0.5])

learning_rate = 0.01

gradient = np.array([0.1, -0.2])

# 가중치 업데이트

weights -= learning_rate*gradient # weights = weights - learning_rate  gradient

print(weights)

[ 0.499 -0.498]


In [ ]:
# 입력값

inputs = np.array([-1.0, 2.0, -0.5, 3.0])

# ReLU 활성화 함수 적용

inputs = np.maximum(0, inputs)

print(inputs)

[0. 2. 0. 3.]


In [ ]:
# 배치 데이터

batch = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 배치 정규화

batch_mean = np.mean(batch, axis=0)

batch_var = np.var(batch, axis=0)

batch -= batch_mean # batch = batch - batch_mean

batch /= np.sqrt(batch_var + 1e-8) # batch = batch / np.sqrt(batch_var + 1e-8)

print(batch)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
import numpy as np

# 예측값과 실제값
y_true = np.array([3, -0, 2, 7])
y_pred = np.array([2.5, 0, 2, 8])

# 샘플 수
n = len(y_true)

# MAE (Mean Absolute Error)
mae = sum(abs(y_true - y_pred)) / n
print(f"MAE: {mae}")

# MSE (Mean Squared Error)
mse = sum((y_true - y_pred) ** 2) / n
print(f"MSE: {mse}")

# RMSE (Root Mean Squared Error)
rmse = (sum((y_true - y_pred) ** 2) / n) ** 0.5
print(f"RMSE: {rmse}")

# RMSLE (Root Mean Squared Logarithmic Error)
# 로그를 계산할 때 Log(0)이 발생하지 않도록 1을 더함
log_true = np.log(y_true + 1)
log_pred = np.log(y_pred + 1)
rmsle = (sum((log_true - log_pred) ** 2) / n) ** 0.5
print(f"RMSLE: {rmsle}")


MAE: 0.375
MSE: 0.3125
RMSE: 0.5590169943749475
RMSLE: 0.08902735015807975


In [ ]:
# 왼 쪽 정 렬
print("{:<10}".format("Alice"))
# 가 운 데 정 렬
print("{:^10}".format("Alice"))
# 오 른 쪽 정 렬
print("{:>10}".format("Alice"))
#Alice
# Alice
# Alice

Alice     
  Alice   
     Alice


In [ ]:
from datetime import datetime
now = datetime.now()
print("The current time is {:%Y-%m-%d %H:%M}.".format(now))

The current time is 2024-06-29 09:54.


In [ ]:
name = "Luten"
age = 34

print("My name is {0} and I am {1} years old. Nice to meet you, {0}.".format(name,age))


My name is Luten and I am 34 years old. Nice to meet you, Luten.


In [ ]:
print("%10s" % "test")  # 10칸 너비의 우측 정렬
print("%-10s" % "test")  # 10칸 너비의 좌측 정렬

      test
test      


In [ ]:
print("%05d" % 42)  # 5자리 정수, 앞을 0으로 채움
print("%.2f" % 3.14159)  # 소수점 둘째 자리까지

00042
3.14


In [ ]:
data = {"name": "Bob", "age": 25}
print("%(name)s is %(age)d years old." % data)

Bob is 25 years old.


In [ ]:
TP = 50
TN = 30
FN = 10
FP = 10

Accuracy = (TP + TN) / (TP + FN + FP + TN)
print(f"Accuracy: {Accuracy:.2f}")

Accuracy: 0.80


In [ ]:
for a in range(0,3):
  for b in range(1,3):
    if a==b:
      break
    print(a,b)


0 1
0 2
2 1


In [ ]:
data = [15, 20, 35, 40, 50]
min_val = min(data)
max_val = max(data)

normalized_data = []
for value in data:
    normalized_value = (value - min_val) / (max_val - min_val)
    normalized_data.append(normalized_value)

print(normalized_data)


[0.0, 0.14285714285714285, 0.5714285714285714, 0.7142857142857143, 1.0]


In [ ]:
from sklearn.model_selection import KFold
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
kf = KFold(n_splits=5)

for train_index, test_index in kf.split(data):
    train_data, test_data = data[train_index], data[test_index]
    print("Train:", train_data, "Test:", test_data)


Train: [ 3  4  5  6  7  8  9 10] Test: [1 2]
Train: [ 1  2  5  6  7  8  9 10] Test: [3 4]
Train: [ 1  2  3  4  7  8  9 10] Test: [5 6]
Train: [ 1  2  3  4  5  6  9 10] Test: [7 8]
Train: [1 2 3 4 5 6 7 8] Test: [ 9 10]


In [ ]:
import numpy as np

# 가상의 데이터와 모델 초기화
data = np.array([[0.1, 0.2], [0.2, 0.3], [0.3, 0.4], [0.4, 0.5]])
labels = np.array([0, 1, 0, 1])
weights = np.random.rand(2)
learning_rate = 0.01

# 간단한 학습 과정
for epoch in range(100):
    for x, y in zip(data, labels):
        prediction = np.dot(x, weights)
        error = prediction - y
        weights -= learning_rate * error * x

print("Final weights:", weights)


Final weights: [0.47814057 0.85441119]


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

true_labels = [0, 1, 1, 0, 1]
predictions = [0, 1, 0, 0, 1]

metrics = {
    "Accuracy": accuracy_score,
    "Precision": precision_score,
    "Recall": recall_score
}

for metric_name, metric_func in metrics.items():
    score = metric_func(true_labels, predictions)
    print(f"{metric_name}: {score}")


Accuracy: 0.8
Precision: 1.0
Recall: 0.6666666666666666


In [ ]:
# 가상의 모델 예측 함수
def predict(x):
    return 1 if np.dot(x, weights) > 0.5 else 0

test_data = np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])
predictions = []

for sample in test_data:
    prediction = predict(sample)
    predictions.append(prediction)

print("Predictions:", predictions)



Predictions: [0, 0, 1]


In [ ]:
for i in range(1, 11):
  if i % 2 == 0:
    print('@', end=' ')
  else:
    print('*', end=' ')

* @ * @ * @ * @ * @ 

In [ ]:
# 숫 자 입 력 받 기
num = int(input("피 라 미 드 의 높 이(층 수)를 입 력 하 세 요: "))
# 피 라 미 드 출 력
for i in range(1, num + 1):
  print(" " * (num - i) + "*" * (2*i - 1))


피 라 미 드 의 높 이(층 수)를 입 력 하 세 요: 10
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************


In [ ]:
# 숫 자 입 력 받 기
num = int(input("숫 자 를 입 력 하 세 요: "))
# 계 단 식 별 찍 기 출 력
for i in range(1, num + 1):
  print("*" * i)

숫 자 를 입 력 하 세 요: 15
*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************
***************


In [ ]:
learning_rate = 0.01

def update_learning_rate(epoch):
  if epoch > 5:
    learning_rate = 0.001

for epoch in range(10):
  update_learning_rate(epoch)

print(learning_rate)

0.01


In [ ]:
def outer(num):
    def inner(data):
        return num * data
    return inner

# 사용 예시
temp = outer(10)
result = temp(5)
print(result)  # 출력: 50

# 함수형 API 스타일로 직접 호출
direct_result = outer(10)(5)
print(direct_result)  # 출력: 50

50
50


In [ ]:
def multiplier(n):
    def multiply(x):
        return n * x
    return multiply

# 사용 예시
double = multiplier(2)
triple = multiplier(3)

print(double(5))  # 출력: 10
print(triple(5))  # 출력: 15

10
15


In [ ]:
import numpy as np

def create_activation_function(function_type):
    def relu(x):
        return np.maximum(0, x)

    def leaky_relu(x, alpha=0.01):
        return np.where(x > 0, x, alpha * x)

    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    if function_type == 'relu':
        return relu
    elif function_type == 'leaky_relu':
        return leaky_relu
    elif function_type == 'sigmoid':
        return sigmoid
    else:
        raise ValueError("Unknown activation function type")

# 사용 예시
relu_activation = create_activation_function('relu')
leaky_relu_activation = create_activation_function('leaky_relu')
sigmoid_activation = create_activation_function('sigmoid')

# 테스트
x = np.array([-2, -1, 0, 1, 2])
print("ReLU:", relu_activation(x))
print("Leaky ReLU:", leaky_relu_activation(x))
print("Sigmoid:", sigmoid_activation(x))


ReLU: [0 0 0 1 2]
Leaky ReLU: [-0.02 -0.01  0.    1.    2.  ]
Sigmoid: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [ ]:
def counter():
    count = 0
    def increment():
        nonlocal count
        count += 1
        return count
    return increment

# 사용 예시
counter1 = counter()
counter2 = counter()

print(counter1())  # 출력: 1
print(counter1())  # 출력: 2
print(counter2())  # 출력: 1
print(counter1())  # 출력: 3

1
2
1
3


In [ ]:
def multiplier(n):
    def multiply(x):
        return n * x
    return multiply

# 사용 예시
double = multiplier(2)
triple = multiplier(3)

print(double(5))  # 출력: 10
print(triple(5))  # 출력: 15

10
15


In [ ]:
import time

def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__} 함수 실행 시간: {end_time - start_time:.5f}초")
        return result
    return wrapper

@timer_decorator
def slow_function(n):
    time.sleep(n)
    return f"{n}초 동안 실행됨"

# 사용
print(slow_function(2))

slow_function 함수 실행 시간: 2.00121초
2초 동안 실행됨


In [ ]:
def func2():
  local_var=200
  print(local_var)

func2()

200


In [ ]:
func2()

200


In [ ]:
print(local_var)

NameError: name 'local_var' is not defined

In [ ]:
def modify_list_elements(lst):
    print(f"함수 내 리스트 주소값 (변경 전): {id(lst)}")
    lst[0] = 99
    print(f"함수 내 리스트 주소값 (변경 후): {id(lst)}")

my_list = [1, 2, 3]
print(f"함수 호출 전 리스트 주소값: {id(my_list)}")
modify_list_elements(my_list)
print(f"함수 호출 후 리스트 주소값: {id(my_list)}")
print(my_list)


함수 호출 전 리스트 주소값: 136803054825920
함수 내 리스트 주소값 (변경 전): 136803054825920
함수 내 리스트 주소값 (변경 후): 136803054825920
함수 호출 후 리스트 주소값: 136803054825920
[99, 2, 3]


In [ ]:
def reassign_list(lst):
    print(f"함수 내 리스트 주소값 (재할당 전): {id(lst)}")
    lst = [4, 5, 6]
    print(f"함수 내 리스트 주소값 (재할당 후): {id(lst)}")

my_list = [1, 2, 3]
print(f"함수 호출 전 리스트 주소값: {id(my_list)}")
reassign_list(my_list)
print(f"함수 호출 후 리스트 주소값: {id(my_list)}")
print(my_list)


함수 호출 전 리스트 주소값: 136803070444864
함수 내 리스트 주소값 (재할당 전): 136803070444864
함수 내 리스트 주소값 (재할당 후): 136803054991360
함수 호출 후 리스트 주소값: 136803070444864
[1, 2, 3]


In [ ]:
def make_url(ip, port=80):
  return "http://{}:{}".format(ip, port)

In [ ]:
make_url("localhost")

'http://localhost:80'

In [ ]:
def func4(a, L=None):
  if L is None:
    L=[]
  L.append(a)
  return L

func4()

TypeError: func4() missing 1 required positional argument: 'a'

In [ ]:
func4(a=40)

[40]

In [ ]:
funct4()

NameError: name 'funct4' is not defined

In [ ]:
def display_info(name, age, country):
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Country: {country}")

# 튜플 정의
info = ("Alice", 30, "USA")

# 튜플 언패킹을 사용하여 함수 호출
display_info(*info)


Name: Alice
Age: 30
Country: USA


In [ ]:
def display_info(name, age, country):
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Country: {country}")

# 딕셔너리 정의
info = {"name": "Alice", "age": 30, "country": "USA"}

# 딕셔너리 언패킹을 사용하여 함수 호출
display_info(**info)


Name: Alice
Age: 30
Country: USA


In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D
from tensorflow.keras.utils import to_categorical

# 데이터 로드 및 전처리
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(-1, 28, 28, 1).astype('float32') / 255
X_test = X_test.reshape(-1, 28, 28, 1).astype('float32') / 255
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# 모델 생성
model = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=1, validation_data=(X_test, y_test))

# 평가
loss, accuracy = model.evaluate(X_test, y_test)
print(f"테스트 정확도: {accuracy * 100:.2f}%")


11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 72s 36ms/step - loss: 0.1540 - accuracy: 0.9551 - val_loss: 0.0646 - val_accuracy: 0.9787
Epoch 2/5
1875/1875 [==============================] - 70s 37ms/step - loss: 0.0536 - accuracy: 0.9837 - val_loss: 0.0488 - val_accuracy: 0.9835
Epoch 3/5
1875/1875 [==============================] - 51s 27ms/step - loss: 0.0353 - accuracy: 0.9887 - val_loss: 0.0447 - val_accuracy: 0.9843
Epoch 4/5
1875/1875 [==============================] - 53s 28ms/step - loss: 0.0240 - accuracy: 0.9921 - val_loss: 0.0550 - val_accuracy: 0.9832
Epoch 5/5
313/313 [==============================] - 4s 12ms/step - loss: 0.0459 - accuracy: 0.9860
테스트 정확도: 98.60%


In [ ]:
import numpy as np
from sklearn.cluster import KMeans

# 데이터 생성
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])

# 모델 생성 및 학습
kmeans = KMeans(n_clusters=2, random_state=0)
kmeans.fit(X)

# 클러스터 센터 출력
print(kmeans.cluster_centers_)  # 출력: [[1. 2.] [4. 2.]]


[[1. 2.]
 [4. 2.]]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 데이터 생성
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([1, 3, 5, 7, 9])

# 모델 생성
model = Sequential()
model.add(Dense(1, input_dim=1, activation='linear'))

# 모델 컴파일
model.compile(optimizer='adam', loss='mse')

# 모델 학습
model.fit(X, y, epochs=100, verbose=0)

# 예측
predictions = model.predict(np.array([[6], [7]]))
print(predictions)  # 출력: [[11.] [13.]]


1/1 [==============================] - 0s 114ms/step
[[-5.7967834]
 [-6.779442 ]]


In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# 데이터 생성
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([0, 0, 0, 1, 1])

# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X, y)

# 예측
predictions = model.predict(np.array([[1.5], [3.5]]))
print(predictions)  # 출력: [0 0]


[0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

# 데이터 생성
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([1, 3, 5, 7, 9])

# 모델 생성 및 학습
model = LinearRegression()
model.fit(X, y)

# 예측
predictions = model.predict(np.array([[6], [7]]))
print(predictions)  # 출력: [11. 13.]


[11. 13.]


In [ ]:
coordinates = [(x, y, z) for x in range(3) for y in range(3) for z in range(3)]
for coord in coordinates:
    print(coord)
# 출력:
# (0, 0, 0)
# (0, 0, 1)
# (0, 0, 2)
# ...
# (2, 2, 0)
# (2, 2, 1)
# (2, 2, 2)


(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)
(0, 2, 0)
(0, 2, 1)
(0, 2, 2)
(1, 0, 0)
(1, 0, 1)
(1, 0, 2)
(1, 1, 0)
(1, 1, 1)
(1, 1, 2)
(1, 2, 0)
(1, 2, 1)
(1, 2, 2)
(2, 0, 0)
(2, 0, 1)
(2, 0, 2)
(2, 1, 0)
(2, 1, 1)
(2, 1, 2)
(2, 2, 0)
(2, 2, 1)
(2, 2, 2)


In [ ]:
import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

password = generate_password(12)
print(password)  # 예: aB3$dE5!hJ1@


T!,b{*QCOtL[


In [ ]:
n = 5
matrix = [[(i+j) % 2 for j in range(n)] for i in range(n)]
for row in matrix:
    print(row)
# 출력:
# [0, 1, 0, 1, 0]
# [1, 0, 1, 0, 1]
# [0, 1, 0, 1, 0]
# [1, 0, 1, 0, 1]
# [0, 1, 0, 1, 0]


[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]


In [ ]:
def rotate_matrix(matrix):
    n = len(matrix)
    rotated = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            rotated[j][n - 1 - i] = matrix[i][j]

    return rotated

# 3x3 행렬 생성
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

rotated_matrix = rotate_matrix(matrix)
for row in rotated_matrix:
    print(row)
# 출력:
# [7, 4, 1]
# [8, 5, 2]
# [9, 6, 3]


[7, 4, 1]
[8, 5, 2]
[9, 6, 3]


In [ ]:
# 3x3 행렬 생성
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 행렬의 모든 요소 합 구하기
total_sum = 0
for row in matrix:
    for element in row:
        total_sum += element

print(total_sum)  # 출력: 45


45


In [ ]:
# 2x2 행렬 생성
matrix = [
    [1, 2],
    [3, 4]
]

# 행렬 출력
for row in matrix:
    print(row)
# 출력:
# [1, 2]
# [3, 4]


[1, 2]
[3, 4]


In [ ]:
# 예시 시계열 데이터
time_series = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 과거 3개의 데이터를 입력으로 사용하고, 다음 데이터를 타겟으로 설정
n_steps = 3
X, y = [], []

for i in range(len(time_series) - n_steps):
    X.append(time_series[i:i+n_steps])
    y.append(time_series[i+n_steps])

X = np.array(X)
y = np.array(y)

print("입력 데이터:\n", X)
print("타겟:\n", y)


입력 데이터:
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
타겟:
 [ 4  5  6  7  8  9 10]


In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# 예시 텍스트 데이터
documents = ["the cat is on the table", "the dog is in the house", "the cat and the dog are friends"]

# 단어 빈도 계산
vectorizer = CountVectorizer()
word_counts = vectorizer.fit_transform(documents).toarray()
word_list = vectorizer.get_feature_names_out()

# 단어 빈도수 계산
tf = word_counts / np.sum(word_counts, axis=1, keepdims=True)
idf = np.log(len(documents) / (np.sum(word_counts > 0, axis=0) + 1))

# TF-IDF 계산
tfidf = [[tf_val * idf_val for tf_val, idf_val in zip(doc_tf, idf)] for doc_tf in tf]

print("TF-IDF 값:\n", tfidf)


TF-IDF 값:
 [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06757751801802739, 0.06757751801802739, -0.09589402415059363], [0.0, 0.0, 0.0, 0.0, 0.0, 0.06757751801802739, 0.06757751801802739, 0.0, 0.0, 0.0, -0.09589402415059363], [0.05792358687259491, 0.05792358687259491, 0.0, 0.0, 0.05792358687259491, 0.0, 0.0, 0.0, 0.0, 0.0, -0.08219487784336597]]


In [ ]:
import pandas as pd

# 예시 데이터프레임
df = pd.DataFrame({
    'feature1': [1, 2, 3, 4, 5],
    'feature2': [6, 7, 8, 9, 10],
    'label': [0, 1, 0, 1, 0]
})

# feature1과 feature2를 추출
features = df[['feature1', 'feature2']]
labels = df['label']

print("특징:\n", features)
print("레이블:\n", labels)

특징:
    feature1  feature2
0         1         6
1         2         7
2         3         8
3         4         9
4         5        10
레이블:
 0    0
1    1
2    0
3    1
4    0
Name: label, dtype: int64


In [ ]:
data = [10, 20, 30, 40, 50]
min_val, max_val = min(data), max(data)
scaled_data = [(x - min_val) / (max_val - min_val) for x in data]
print(scaled_data)


[0.0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
data = [1, 2, None, 4, None, 6]
filled_data = [x if x is not None else 0 for x in data]
print(filled_data)


[1, 2, 0, 4, 0, 6]


In [ ]:
from sklearn.model_selection import KFold
import numpy as np

# 데이터셋
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])
labels = np.array([0, 1, 0, 1])

# K-겹 교차 검증 설정
kf = KFold(n_splits=2)

for train_index, test_index in kf.split(data):
    # 훈련 및 테스트 데이터 복사
    X_train, X_test = data[train_index].copy(), data[test_index].copy()
    y_train, y_test = labels[train_index].copy(), labels[test_index].copy()

    print("훈련 데이터:\n", X_train)
    print("테스트 데이터:\n", X_test)


훈련 데이터:
 [[5 6]
 [7 8]]
테스트 데이터:
 [[1 2]
 [3 4]]
훈련 데이터:
 [[1 2]
 [3 4]]
테스트 데이터:
 [[5 6]
 [7 8]]


In [ ]:
import numpy as np

# 원본 데이터셋
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# 데이터 복사 및 타입 변환
augmented_data = data.astype(np.float64).copy()

# 데이터 증강 (예: 각 행에 무작위 노이즈 추가)
noise = np.random.normal(0, 1, data.shape)
augmented_data += noise

# 데이터 타입 및 형식 확인
print("원본 데이터셋의 데이터 타입:", data.dtype)
print("증강된 데이터셋의 데이터 타입:", augmented_data.dtype)
print("원본 데이터셋의 형식:", data.shape)
print("증강된 데이터셋의 형식:", augmented_data.shape)

print("원본 데이터셋:\n", data)
print("증강된 데이터셋:\n", augmented_data)


원본 데이터셋의 데이터 타입: int64
증강된 데이터셋의 데이터 타입: float64
원본 데이터셋의 형식: (3, 2)
증강된 데이터셋의 형식: (3, 2)
원본 데이터셋:
 [[1 2]
 [3 4]
 [5 6]]
증강된 데이터셋:
 [[1.79564735 3.20413694]
 [2.76654356 2.88582232]
 [5.84484049 6.0671068 ]]


In [ ]:
import numpy as np

# 원본 데이터셋
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 데이터셋 복사
processed_data = data.copy()

# 전처리 작업 (예: 모든 값을 2배로 증가)
processed_data = processed_data * 2

print("원본 데이터셋:\n", data)
print("전처리된 데이터셋:\n", processed_data)



원본 데이터셋:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
전처리된 데이터셋:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
categories = ['apple', 'banana', 'apple', 'cherry']
unique_categories = list(set(categories))
one_hot_encoded = [[1 if category == unique else 0 for unique in unique_categories] for category in categories]
print(one_hot_encoded)



[[0, 1, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [ ]:
import numpy as np

# 예시 데이터셋 (10개의 샘플, 각 샘플은 2개의 특징을 가짐)
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10],
    [11, 12],
    [13, 14],
    [15, 16],
    [17, 18],
    [19, 20]
])

# 80%는 훈련 세트, 20%는 테스트 세트로 분할
train_data = data[:8]
test_data = data[8:]

print("훈련 세트:\n", train_data)
print("테스트 세트:\n", test_data)

# 데이터셋 복사
processed_data = data.copy()

# 전처리 작업 (예: 모든 값을 2배로 증가)
processed_data = processed_data * 2

print("원본 데이터셋:\n", data)
print("전처리된 데이터셋:\n", processed_data)

훈련 세트:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
테스트 세트:
 [[17 18]
 [19 20]]
원본 데이터셋:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
전처리된 데이터셋:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]
 [30 32]
 [34 36]
 [38 40]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# 아이리스 데이터셋 로드
iris = load_iris()
X, y = iris.data, iris.target

# 랜덤 포레스트 모델 훈련
model = RandomForestClassifier(n_estimators=100)
model.fit(X, y)

# 특성 중요도 추출
feature_importances = model.feature_importances_
feature_names = iris.feature_names

# 특성 중요도를 기준으로 정렬
sorted_features = sorted(zip(feature_importances, feature_names), reverse=True)

print("특성 중요도 순위:")
for importance, name in sorted_features:
    print(f"{name}: {importance:.4f}")


특성 중요도 순위:
petal length (cm): 0.4492
petal width (cm): 0.4367
sepal length (cm): 0.0898
sepal width (cm): 0.0243


In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# 예시 데이터
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])

# 로지스틱 회귀 모델 훈련
model = LogisticRegression()
model.fit(X, y)

# 새로운 데이터에 대한 예측 확률 계산
new_data = np.array([[2, 3]])
proba = model.predict_proba(new_data)[0]

# 예측 확률을 기준으로 클래스 정렬
sorted_proba = sorted(zip(model.classes_, proba), key=lambda x: x[1], reverse=True)

print("예측 확률 순위:")
for cls, prob in sorted_proba:
    print(f"클래스 {cls}: {prob:.4f}")


예측 확률 순위:
클래스 0: 0.6667
클래스 1: 0.3333


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_wine
import numpy as np

# 와인 데이터셋 로드
wine = load_wine()
X, y = wine.data, wine.target

# 결정 트리 모델 생성
model = DecisionTreeClassifier()

# 5-겹 교차 검증 점수 계산
cv_scores = cross_val_score(model, X, y, cv=5)

# 교차 검증 점수를 정렬
sorted_cv_scores = sorted(cv_scores, reverse=True)

print("교차 검증 점수 (내림차순):")
for i, score in enumerate(sorted_cv_scores):
    print(f"Fold {i+1}: {score:.4f}")


교차 검증 점수 (내림차순):
Fold 1: 0.9444
Fold 2: 0.9444
Fold 3: 0.9143
Fold 4: 0.8571
Fold 5: 0.8056


In [ ]:
a=10
print(a)

10


In [ ]:
10=a

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (<ipython-input-2-eec0abb80e33>, line 1)

In [ ]:
int a = 10

SyntaxError: invalid syntax (<ipython-input-3-392d75864529>, line 1)

In [ ]:
x=100
print(x)

100


In [ ]:
print(id(x))

132861328280912


In [ ]:
a, b = 10, 20
print(a+b)

30


In [ ]:
a, b = 10,20
a, b = b, a+b

In [ ]:
a, b

(20, 30)

In [ ]:
a, b =10,20
a=b
b= a+b

In [ ]:
a, b

(20, 40)

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [ ]:
print("Hello", "world", sep="-")

Hello-world


In [ ]:
with open("output.txt", "w") as f:
  print("Hello, file!", file=f)

In [ ]:
/content/output.txt

In [ ]:
name = '홍길동'
age=20

print(name, '님의 나이는 ', age, ' 입니다', sep='')

홍길동님의 나이는 20 입니다


In [ ]:
int('FACE', 16)

64206

In [ ]:
int('FACE', 10)

ValueError: invalid literal for int() with base 10: 'FACE'

In [ ]:
first_number = int(input("첫번쨰 숫자 : "))

second_number = int(input("두번쨰 숫자 : "))

print(first_number + second_number)

첫번쨰 숫자 : 10
두번쨰 숫자 : 20
30


In [ ]:
print("Hello\nWorld")

Hello
World


In [ ]:
S="Today fine"

S[a:n]

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 데이터 생성
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

# 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터 생성
X = np.random.rand(100, 10)
y = np.random.randint(2, size=100)

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 모델 생성
model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(1, activation='sigmoid')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train, epochs=10, batch_size=32)

# 모델 평가
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy}')


Epoch 1/10
3/3 [==============================] - 1s 6ms/step - loss: 0.7560 - accuracy: 0.4875
Epoch 2/10
3/3 [==============================] - 0s 4ms/step - loss: 0.7379 - accuracy: 0.4875
Epoch 3/10
3/3 [==============================] - 0s 3ms/step - loss: 0.7211 - accuracy: 0.4875
Epoch 4/10
3/3 [==============================] - 0s 4ms/step - loss: 0.7104 - accuracy: 0.5000
Epoch 5/10
3/3 [==============================] - 0s 4ms/step - loss: 0.7031 - accuracy: 0.5125
Epoch 6/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6961 - accuracy: 0.5250
Epoch 7/10
3/3 [==============================] - 0s 4ms/step - loss: 0.6932 - accuracy: 0.5500
Epoch 8/10
3/3 [==============================] - 0s 3ms/step - loss: 0.6893 - accuracy: 0.5125
Epoch 9/10
3/3 [==============================] - 0s 3ms/step - loss: 0.6866 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 136ms/step - loss: 0.7101 - accuracy: 0.4500
Accuracy: 0.44999998807907104


In [ ]:
import pandas as pd

# 가상의 데이터프레임 생성
data = {
    'feature1': [1, 2, 3, 4, 5],
    'feature2': [10, 20, 30, 40, 50],
    'feature3': [100, 200, 300, 400, 500]
}
df = pd.DataFrame(data)

# 각 컬럼의 요약 통계 계산
summary_stats = df.describe()

# 요약 통계 출력
for column in df.columns:
    mean = summary_stats.at['mean', column]
    std = summary_stats.at['std', column]
    min_val = summary_stats.at['min', column]
    max_val = summary_stats.at['max', column]
    formatted_string = "Feature: {}, Mean: {:.2f}, Std: {:.2f}, Min: {:.2f}, Max: {:.2f}".format(
        column, mean, std, min_val, max_val)
    print(formatted_string)


Feature: feature1, Mean: 3.00, Std: 1.58, Min: 1.00, Max: 5.00
Feature: feature2, Mean: 30.00, Std: 15.81, Min: 10.00, Max: 50.00
Feature: feature3, Mean: 300.00, Std: 158.11, Min: 100.00, Max: 500.00


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# 가상의 실제 값과 예측 값
y_true = [0, 1, 1, 0, 1, 0, 1, 1]
y_pred = [0, 0, 1, 0, 1, 1, 1, 1]

# 평가 지표 계산
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

# 평가 결과 포맷팅 및 출력
formatted_string = ("Accuracy: {:.2f}, Precision: {:.2f}, Recall: {:.2f}, F1 Score: {:.2f}"
                    .format(accuracy, precision, recall, f1))
print(formatted_string)


Accuracy: 0.75, Precision: 0.80, Recall: 0.80, F1 Score: 0.80


In [ ]:
import pandas as pd
from collections import Counter

# 가상의 데이터프레임 생성
data = {
    'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'feature2': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'label': [0, 0, 1, 1, 1, 0, 0, 0, 1, 1]
}
df = pd.DataFrame(data)

# 클래스 비율 계산
class_counts = Counter(df['label'])
total_count = len(df)

# 클래스 비율 출력
for class_label, count in class_counts.items():
    percentage = (count / total_count) * 100
    print(f"Class {class_label}: {count} samples ({percentage:.2f}%)")


Class 0: 5 samples (50.00%)
Class 1: 5 samples (50.00%)


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# 데이터셋 로드
iris = load_iris()
X, y = iris.data, iris.target

# 모델 정의
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 교차 검증 수행
scores = cross_val_score(model, X, y, cv=5)

# 각 폴드의 결과 출력
for fold_idx, score in enumerate(scores, 1):
    print(f"Fold {fold_idx}: Accuracy = {score:.4f}")

# 평균 성능 출력
mean_score = scores.mean()
print(f"Mean Accuracy: {mean_score:.4f}")


Fold 1: Accuracy = 0.9667
Fold 2: Accuracy = 0.9667
Fold 3: Accuracy = 0.9333
Fold 4: Accuracy = 0.9667
Fold 5: Accuracy = 1.0000
Mean Accuracy: 0.9667


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr1)

[1 2 3 4 5]


In [ ]:
# 1. 튜플 생성 및 타입 확인
single_tuple = (3,)
print(type(single_tuple))  # 출력: <class 'tuple'>

# 일반 괄호와의 차이
not_tuple = (3)
print(type(not_tuple))  # 출력: <class 'int'>

# 2. 튜플 언패킹
a, = (3,)
print(a)  # 출력: 3

# 3. 함수에서 단일 요소 튜플 반환
def get_single_item():
    return (3,)

result = get_single_item()
print(result)  # 출력: (3,)

# 4. 튜플 연산
single_tuple = (3,)
expanded_tuple = single_tuple * 3
print(expanded_tuple)  # 출력: (3, 3, 3)

# 5. 집합(set)에서의 사용
unique_items = {(1,), (2,), (3,)}
print(unique_items)  # 출력: {(1,), (2,), (3,)}

<class 'tuple'>
<class 'int'>
3
(3,)
(3, 3, 3)
{(1,), (2,), (3,)}


In [ ]:
import numpy as np
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np

data = np.array([10,20,30,40,50])
data -= np.min(data)
data /= np.max(data)

print("정규화된 데이터 : ", data)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
#6 두 불리언 값에 대해 AND 연산 수행 후 결과 출력
bool1 = bool(input("첫 번째 불리언 값 입력:"))
bool2 = bool(input("두 번째 불리언 값 입력:"))

result = bool1 & bool2
print("and연산 결과:", result)

첫 번째 불리언 값 입력:False
두 번째 불리언 값 입력:False
and연산 결과: True


In [ ]:
bool1

True

In [ ]:
bool2

True

In [ ]:
bool()

False

In [ ]:
bool(0)

False

In [ ]:
bool(False)

False

In [ ]:
bool(1)

True

In [ ]:
bool('1')

True

In [ ]:
bool(False)&bool(False)

False

In [ ]:
bool(False)|bool(False)


False

In [ ]:
def print_args(*args):
    for arg in args:
        print(arg)

print_args(1, 2, 3)
print_args('a', 'b', 'c')


1
2
3
a
b
c


In [ ]:
def print_kwargs(**kwargs):
    for key, value in kwargs.items():
        print(f"{key} = {value}")

print_kwargs(name="Alice", age=30, city="New York")
print_kwargs(fruit="Apple", color="Red", price=1.5)


name = Alice
age = 30
city = New York
fruit = Apple
color = Red
price = 1.5


In [ ]:
def print_args_kwargs(*args, **kwargs):
    print("Arguments:", args)
    print("Keyword Arguments:", kwargs)

print_args_kwargs(1, 2, 3, name="Alice", age=30)


Arguments: (1, 2, 3)
Keyword Arguments: {'name': 'Alice', 'age': 30}


In [ ]:
def print_args(fixed_arg, *args):
    print("고정 인자:", fixed_arg)
    for arg in args:
        print("가변 인자:", arg)

print_args("고정", 1, 2, 3)
# 출력:
# 고정 인자: 고정
# 가변 인자: 1
# 가변 인자: 2
# 가변 인자: 3

고정 인자: 고정
가변 인자: 1
가변 인자: 2
가변 인자: 3


In [ ]:
def calculate_area(shape, *dimensions):
    if shape == 'rectangle':
        length, width = dimensions
        area = length * width
    elif shape == 'circle':
        radius, = dimensions
        area = 3.14 * radius ** 2
    else:
        area = None
        print(f"Unsupported shape: {shape}")
    return area

# 사용 예시
print(calculate_area('rectangle', 5, 10))  # 50.0
print(calculate_area('circle', 3))  # 28.26
print(calculate_area('triangle', 3, 4))  # Unsupported shape: triangle


50
28.26
Unsupported shape: triangle
None


In [ ]:
def print_person_info(name, age, **kwargs):
    print(f"Name: {name}, Age: {age}")
    for key, value in kwargs.items():
        print(f"{key.capitalize()}: {value}")

# 사용 예시
print_person_info("Alice", 25)
print_person_info("Bob", 30, occupation="Engineer", city="New York")
print_person_info("Charlie", 35, occupation="Manager", city="London", hobbies="Reading, Hiking")



Name: Alice, Age: 25
Name: Bob, Age: 30
Occupation: Engineer
City: New York
Name: Charlie, Age: 35
Occupation: Manager
City: London
Hobbies: Reading, Hiking


In [ ]:
def calculate_area(shape, *dimensions):
    if shape == 'rectangle':
        length, width = dimensions
        area = length * width
    elif shape == 'circle':
        radius, = dimensions
        area = 3.14 * radius ** 2
    return area

print(calculate_area('rectangle', (5, 10)))  # 50.0
print(calculate_area('circle', (3,)))  # 28.26


ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
def print_numbers(*args):
    for arg in args:
        print(arg)

print_numbers(1, 2, 3)  # 1, 2, 3
print_numbers((4, 5), 6, [7, 8])  # (4, 5), 6, [7, 8]


1
2
3
(4, 5)
6
[7, 8]


In [ ]:
def calculate_volume(length, width, height):
    return length * width * height

dimensions = (5, 10, 3)
volume = calculate_volume(*dimensions)
print(volume)  # 150


150


In [ ]:
def greet(first_name, last_name):
    print(f"Hello, {first_name} {last_name}!")

# 딕셔너리 생성
person = {'first_name': 'John', 'last_name': 'Doe'}

# 딕셔너리 언패킹하여 함수 호출
greet(**person)


Hello, John Doe!


In [ ]:
def introduce(name, age, city):
    print(f"My name is {name}, I am {age} years old and I live in {city}.")

# 딕셔너리 생성
info = {'name': 'Alice', 'age': 30, 'city': 'New York'}

# 딕셔너리 언패킹하여 함수 호출
introduce(**info)


My name is Alice, I am 30 years old and I live in New York.


In [ ]:
def print_info(name, age, city='Unknown'):
    print(f"Name: {name}, Age: {age}, City: {city}")

# 딕셔너리 생성
person_info = {'name': 'Bob', 'age': 25}

# 딕셔너리 언패킹하여 함수 호출
print_info(**person_info)


Name: Bob, Age: 25, City: Unknown


In [ ]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x**2, numbers))
print(squared_numbers)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


In [ ]:
students = [{'name': 'John', 'grade': 90},
            {'name': 'Jane', 'grade': 85},
            {'name': 'Dave', 'grade': 92}]
sorted_students = sorted(students, key=lambda x: x['grade'])
print(sorted_students)
# Output: [{'name': 'Jane', 'grade': 85}, {'name': 'John', 'grade': 90}, {'name': 'Dave', 'grade': 92}]


[{'name': 'Jane', 'grade': 85}, {'name': 'John', 'grade': 90}, {'name': 'Dave', 'grade': 92}]


In [ ]:
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  # Output: [2, 4, 6]


[2, 4, 6]


In [ ]:
import random

target = random.randint(1, 100)
guess = None
attempts = 0

while guess != target:
    guess = int(input("Guess the number (between 1 and 100): "))
    attempts += 1
    if guess < target:
        print("Too low!")
    elif guess > target:
        print("Too high!")
    else:
        print(f"Congratulations! You've guessed the number in {attempts} attempts.")

In [ ]:
animals = ["고양이", "강아지", "코끼리", "기린", "사자"]
target = random.choice(animals)
attempts = 0

print("제가 생각한 동물을 맞춰보세요.")

while True:
    guess = input("동물 이름을 입력하세요: ")
    attempts += 1

    if guess.lower() == target.lower():
        print(f"정답입니다! {attempts}번 만에 맞추셨습니다.")
        break
    else:
        print("틀렸습니다. 다시 시도해보세요.")

    if attempts % 5 == 0:
        print(f"힌트: 첫 글자는 '{target[0]}'입니다.")

제가 생각한 동물을 맞춰보세요.
동물 이름을 입력하세요: 고양이
틀렸습니다. 다시 시도해보세요.
동물 이름을 입력하세요: 캣
틀렸습니다. 다시 시도해보세요.
동물 이름을 입력하세요: cat
틀렸습니다. 다시 시도해보세요.
동물 이름을 입력하세요: 강아지
틀렸습니다. 다시 시도해보세요.
동물 이름을 입력하세요: 코끼리
정답입니다! 5번 만에 맞추셨습니다.


In [ ]:
# 사용자에게 입력을 받아 'quit'을 입력할 때까지 계속 입력을 받는 예시
while True:
    user_input = input("Type 'quit' to exit: ")
    if user_input.lower() == 'quit':
        break
    print("You typed:", user_input)

Type 'quit' to exit: ㄳ
You typed: ㄳ
Type 'quit' to exit: ㅗㄹ
You typed: ㅗㄹ
Type 'quit' to exit: ㅈㄷㄱ
You typed: ㅈㄷㄱ
Type 'quit' to exit: quit


In [ ]:
for i in range(2,10):
  for j in range(1,10):
    print(i*j, end=' ')
  print()

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


In [ ]:
for i in range(1,10):
  for j in range(2,10):
    print(i*j, end=' ')
  print()

2 3 4 5 6 7 8 9 
4 6 8 10 12 14 16 18 
6 9 12 15 18 21 24 27 
8 12 16 20 24 28 32 36 
10 15 20 25 30 35 40 45 
12 18 24 30 36 42 48 54 
14 21 28 35 42 49 56 63 
16 24 32 40 48 56 64 72 
18 27 36 45 54 63 72 81 


In [ ]:
# 학생 성적 딕셔너리
student_grades = {
    'Alice': 85,
    'Bob': 90,
    'Charlie': 78,
    'David': 92
}

# 특정 학생의 성적 조회
alice_grade = student_grades['Alice']
print(f"Alice's grade: {alice_grade}")

# 모든 학생의 성적 조회
print("All students' grades:")
for grade in student_grades.values():
    print(grade)


Alice's grade: 85
All students' grades:
85
90
78
92


In [ ]:
import random

list_label = ['사람', '동물', '동물', '동물', '동물', '사람', '사람', '사람']
list_value = ['수진', '기린', '코끼리', '강아지', '고양이', '민호', '지민', '동준']
guess = None
attempts = 0

while guess != False :
  target = random.randint(0, (len(list_label)-1))
  guess = input(f"이름({list_value[target]})을 보고 사람인지 동물인지 맞춰봐 ! : ")
  attempts += 1
  if guess == list_label[target] :
    print("잘 맞췄네!")
  elif guess != list_label[target] :
    print("다시 생각해봐...")
  else :
    print(f"잘했어 ! {list_value[target]}은 {list_label[target]}이야 ! ")
    list_value.remove(list_value[target])
    list_label.remove(list_label[target])
  print(list_value, list_label)
  if attempts >= 5 :
    print(f"벌써 {attempts}번 맞췄네 ! 훌륭해 !")
    break

이름(민호)을 보고 사람인지 동물인지 맞춰봐 ! : 사람
잘 맞췄네!
['수진', '기린', '코끼리', '강아지', '고양이', '민호', '지민', '동준'] ['사람', '동물', '동물', '동물', '동물', '사람', '사람', '사람']
이름(수진)을 보고 사람인지 동물인지 맞춰봐 ! : 사람
잘 맞췄네!
['수진', '기린', '코끼리', '강아지', '고양이', '민호', '지민', '동준'] ['사람', '동물', '동물', '동물', '동물', '사람', '사람', '사람']
이름(동준)을 보고 사람인지 동물인지 맞춰봐 ! : 수진
다시 생각해봐...
['수진', '기린', '코끼리', '강아지', '고양이', '민호', '지민', '동준'] ['사람', '동물', '동물', '동물', '동물', '사람', '사람', '사람']


KeyboardInterrupt: Interrupted by user

In [ ]:
import random

list_label = ['사람', '동물', '동물', '동물', '동물', '사람', '사람', '사람']
list_value = ['수진', '기린', '코끼리', '강아지', '고양이', '민호', '지민', '동준']
guess = None
attempts = 0

while True:
    if len(list_label) == 0:
        print("모든 항목을 맞췄습니다!")
        break

    target = random.randint(0, len(list_label) - 1)
    guess = input(f"이름({list_value[target]})을 보고 사람인지 동물인지 맞춰봐! : ")
    attempts += 1

    if guess == list_label[target]:
        print("잘 맞췄네!")
        list_value.pop(target)
        list_label.pop(target)
        print(list_value, list_label)
    elif guess != list_label[target]:
        print("다시 생각해봐...")

    if attempts >= 5:
        print(f"벌써 {attempts}번 시도했네! 훌륭해!")
        break


이름(고양이)을 보고 사람인지 동물인지 맞춰봐! : 동물
잘 맞췄네!
['수진', '기린', '코끼리', '강아지', '민호', '지민', '동준'] ['사람', '동물', '동물', '동물', '사람', '사람', '사람']
이름(지민)을 보고 사람인지 동물인지 맞춰봐! : 사람
잘 맞췄네!
['수진', '기린', '코끼리', '강아지', '민호', '동준'] ['사람', '동물', '동물', '동물', '사람', '사람']
이름(기린)을 보고 사람인지 동물인지 맞춰봐! : 동물
잘 맞췄네!
['수진', '코끼리', '강아지', '민호', '동준'] ['사람', '동물', '동물', '사람', '사람']
이름(민호)을 보고 사람인지 동물인지 맞춰봐! : 사람
잘 맞췄네!
['수진', '코끼리', '강아지', '동준'] ['사람', '동물', '동물', '사람']


KeyboardInterrupt: Interrupted by user

In [ ]:
import random

choices = ["가위", "바위", "보"]
score = {"player": 1, "computer": 1}
print(score['player'],score['computer'])


1 1


In [ ]:
import random

choices = ["가위", "바위", "보"]
score = {"player": 0, "computer": 0}
print("최초 스코아 세팅", score['player'],score['computer'])

while True:
    player = input("가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): ")
    if player == "끝":
      break

    if player not in choices:
      print("잘못된 입력입니다. 다시 시도하세요.")
      continue

    computer = random.choice(choices)
    print(f"컴퓨터의 선택: {computer}")

    if player == computer:
      print("무승부!")
      score["player"] += 1
      score["computer"] += 1


    elif(player == "가위" and computer == "보") or \
      (player == "바위" and computer == "가위") or \
      (player == "보" and computer == "바위"):
      print("플레이어 승!")
      score["player"] += 1
    else:
      print("컴퓨터 승!")
      score["computer"] += 1
      print(score['player'],score['computer'])

print("최종 스코아", score['player'], score['computer'])


0 0
가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): 가위
컴퓨터의 선택: 보
플레이어 승!
가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): 바위
컴퓨터의 선택: 가위
플레이어 승!
가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): 보
컴퓨터의 선택: 보
무승부!
가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): 가위
컴퓨터의 선택: 가위
무승부!
가위, 바위, 보 중 하나를 선택하세요 (종료하려면 '끝' 입력): 끝
최종 스코아 2 0


In [ ]:
print()

In [ ]:
a = print()
print(a)


None


In [ ]:
a = print("간다")
print(a)

간다
None


In [ ]:
import random

# 로또 번호 생성 함수 (스토리 추가)
def generate_lotto_numbers(theme):
    if theme == 'adventure':
        numbers = random.sample(range(1, 46), 6)
        numbers.sort()  # 번호 정렬
        return numbers
    elif theme == 'fantasy':
        # 1부터 50까지의 숫자 중 6개를 선택 (허용되지 않는 숫자도 선택 가능)
        numbers = [random.randint(1, 50) for _ in range(6)]
        return numbers
    elif theme == 'sci-fi':
        # 1부터 60까지의 숫자 중 6개를 선택 (특정 규칙을 따라 선택 가능)
        numbers = []
        while len(numbers) < 6:
            number = random.randint(1, 60)
            if number % 2 == 0:  # 짝수만 선택
                numbers.append(number)
        numbers.sort()  # 번호 정렬
        return numbers
    else:
        raise ValueError("지원되지 않는 테마입니다.")

# 로또 티켓 생성 함수
def generate_lotto_tickets(ticket_count, theme):
    tickets = []
    for _ in range(ticket_count):
        ticket = generate_lotto_numbers(theme)
        tickets.append(ticket)
    return tickets

# 메인 함수
def main():
    print("로또 테마를 선택하세요:")
    print("1. 모험 (Adventure)")
    print("2. 판타지 (Fantasy)")
    print("3. 과학 판타지 (Sci-Fi)")
    choice = input("테마를 선택하세요 (1, 2, 3 중 하나): ")

    if choice == '1':
        theme = 'adventure'
    elif choice == '2':
        theme = 'fantasy'
    elif choice == '3':
        theme = 'sci-fi'
    else:
        print("유효하지 않은 선택입니다.")
        return

    try:
        ticket_count = int(input("생성할 로또 티켓의 수를 입력하세요: "))
        if ticket_count <= 0:
            print("1 이상의 수를 입력하세요.")
            return

        tickets = generate_lotto_tickets(ticket_count, theme)

        print("\n생성된 로또 티켓 번호:")
        for idx, ticket in enumerate(tickets, start=1):
            print(f"티켓 {idx}: {ticket}")
    except ValueError as e:
        print(f"오류 발생: {e}")

if __name__ == "__main__":
    main()


로또 테마를 선택하세요:
1. 모험 (Adventure)
2. 판타지 (Fantasy)
3. 과학 판타지 (Sci-Fi)
테마를 선택하세요 (1, 2, 3 중 하나): 2
생성할 로또 티켓의 수를 입력하세요: 5

생성된 로또 티켓 번호:
티켓 1: [16, 13, 16, 45, 16, 48]
티켓 2: [9, 4, 37, 4, 24, 2]
티켓 3: [25, 24, 43, 22, 25, 32]
티켓 4: [29, 31, 47, 3, 35, 26]
티켓 5: [8, 38, 33, 33, 43, 31]


In [ ]:
def decimal_to_binary_hex(decimal_num):
    # 10진수를 2진수로 변환
    binary = bin(decimal_num)[2:]  # [2:]는 '0b' 접두사를 제거합니다

    # 10진수를 16진수로 변환
    hexadecimal = hex(decimal_num)[2:]  # [2:]는 '0x' 접두사를 제거합니다

    return binary, hexadecimal

# 사용자로부터 10진수 입력 받기
while True:
    try:
        decimal_input = int(input("10진수를 입력하세요 (종료하려면 'q' 입력): "))
        binary_result, hex_result = decimal_to_binary_hex(decimal_input)

        print(f"10진수: {decimal_input}")
        print(f"2진수: {binary_result}")
        print(f"16진수: {hex_result}")
        print()
    except ValueError:
        user_input = input("올바른 숫자를 입력하세요. 종료하려면 'q'를 입력하세요: ")
        if user_input.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

10진수를 입력하세요 (종료하려면 'q' 입력): 100
10진수: 100
2진수: 1100100
16진수: 64

10진수를 입력하세요 (종료하려면 'q' 입력): 500
10진수: 500
2진수: 111110100
16진수: 1f4

10진수를 입력하세요 (종료하려면 'q' 입력): q
올바른 숫자를 입력하세요. 종료하려면 'q'를 입력하세요: q
프로그램을 종료합니다.


In [ ]:
import calendar

def print_calendar(year, month):
    # 달력 객체 생성
    cal = calendar.monthcalendar(year, month)

    # 월 이름과 연도 출력
    print(f"{calendar.month_name[month]} {year}".center(20))
    print("Mo Tu We Th Fr Sa Su")

    # 주 단위로 날짜 출력
    for week in cal:
        week_str = ""
        for day in week:
            if day == 0:
                week_str += "   "
            else:
                week_str += f"{day:2d} "
        print(week_str)

def main():
    while True:
        try:
            year = int(input("연도를 입력하세요 (예: 2024): "))
            month = int(input("월을 입력하세요 (1-12): "))

            if 1 <= month <= 12:
                print_calendar(year, month)
                break
            else:
                print("올바른 월(1-12)을 입력하세요.")
        except ValueError:
            print("올바른 숫자를 입력하세요.")

if __name__ == "__main__":
    main()

연도를 입력하세요 (예: 2024): 2024
월을 입력하세요 (1-12): 7
     July 2024      
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7 
 8  9 10 11 12 13 14 
15 16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31             


In [ ]:
def manage_library_books():
    # 초기 도서 목록
    books = ["해리 포터", "반지의 제왕", "일리아드", "오디세이", "위대한 개츠비"]
    print("현재 도서관 장서:", books)

    # 새 책 입고
    new_book = "호빗"
    books.append(new_book)
    print(f"'{new_book}'이(가) 새로 입고되었습니다. 현재 장서:", books)

    # 특정 위치에 책 삽입
    classic_book = "돈키호테"
    books.insert(2, classic_book)
    print(f"'{classic_book}'을(를) 세 번째 위치에 배치했습니다. 현재 장서:", books)

    # 대출된 책 제거
    borrowed_book = books.pop(1)
    print(f"'{borrowed_book}'이(가) 대출되었습니다. 남은 장서:", books)

    # 분실된 책 제거
    lost_book = "오디세이"
    if lost_book in books:
        books.remove(lost_book)
        print(f"'{lost_book}'이(가) 분실되어 목록에서 제거되었습니다. 현재 장서:", books)
    else:
        print(f"'{lost_book}'은(는) 현재 도서 목록에 없습니다.")

    # 책 정렬
    books.sort()
    print("책을 알파벳 순으로 정리했습니다:", books)

    # 책 목록 뒤집기 (최신 입고 순으로 변경)
    books.reverse()
    print("최근 입고된 순서대로 책을 재배열했습니다:", books)

    # 상위 3권 책 선택 (인기 도서)
    top_books = books[:3]
    print("이번 주 인기 도서 Top 3:", top_books)

    # 도서관 장서 수 확인
    book_count = len(books)
    print(f"현재 도서관에는 총 {book_count}권의 책이 있습니다.")

    # 복본 책 확인
    duplicate_book = "해리 포터"
    books.append(duplicate_book)
    duplicate_count = books.count(duplicate_book)
    print(f"'{duplicate_book}'의 복본은 {duplicate_count}권 있습니다.")

    # 특정 책의 위치 찾기
    search_book = "위대한 개츠비"
    if search_book in books:
        book_index = books.index(search_book)
        print(f"'{search_book}'은(는) 목록의 {book_index + 1}번째에 있습니다.")
    else:
        print(f"'{search_book}'은(는) 현재 도서 목록에 없습니다.")

    # 새로운 기증 도서 목록 추가
    donated_books = ["1984", "동물농장"]
    books.extend(donated_books)
    print("기증받은 도서를 추가했습니다. 현재 전체 장서:", books)

    # 도서 목록 백업
    books_backup = books.copy()
    print("도서 목록이 백업되었습니다.")

    # 도서관 리모델링으로 인한 임시 폐관 (목록 초기화)
    books.clear()
    print("도서관 리모델링으로 모든 책이 보관되었습니다. 현재 서가:", books)
    print("백업된 도서 목록:", books_backup)

if __name__ == "__main__":
    manage_library_books()

In [ ]:
def get_user_info():
    return ("Alice", 30, "alice@example.com")

name, age, email = get_user_info()
print(f"Name: {name}, Age: {age}, Email: {email}")

Name: Alice, Age: 30, Email: alice@example.com


In [ ]:
def calculate_distance(point1, point2):
    return ((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)**0.5

point_a = (0, 0)
point_b = (3, 4)
distance = calculate_distance(point_a, point_b)
print(f"Distance: {distance}")

Distance: 5.0


In [ ]:
student_grades = {
    ("John", "Doe"): 85,
    ("Jane", "Smith"): 92,
    ("Bob", "Johnson"): 78
}

print(student_grades[("Jane", "Smith")])

92


In [ ]:
DAYS_OF_WEEK = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

def is_weekend(day):
    return day in DAYS_OF_WEEK[-2:]

print(is_weekend("Saturday"))

True


In [ ]:
def print_person_info(info):
    name, age, occupation = info
    print(f"{name} is {age} years old and works as a {occupation}")

person_info = ("Charlie", 35, "Engineer")
print_person_info(person_info)

Charlie is 35 years old and works as a Engineer


In [ ]:
numbers = (1, 2, 3, 4, 5)
first, *middle, last = numbers
print(f"First: {first}, Middle: {middle}, Last: {last}")

First: 1, Middle: [2, 3, 4], Last: 5


In [ ]:
def fetch_user_records():
    return [
        (1, "Alice", "alice@example.com"),
        (2, "Bob", "bob@example.com"),
        (3, "Charlie", "charlie@example.com")
    ]

for user_id, name, email in fetch_user_records():
    print(f"ID: {user_id}, Name: {name}, Email: {email}")

ID: 1, Name: Alice, Email: alice@example.com
ID: 2, Name: Bob, Email: bob@example.com
ID: 3, Name: Charlie, Email: charlie@example.com


In [ ]:
HTTP_STATUS_CODES = (200, 201, 204, 400, 401, 403, 404, 500)

def is_success(status_code):
    return status_code in HTTP_STATUS_CODES[:3]

print(is_success(200))

True


In [ ]:
def swap(a, b):
    return b, a

x, y = 10, 20
print(f"Before swap: x = {x}, y = {y}")
x, y = swap(x, y)
print(f"After swap: x = {x}, y = {y}")

Before swap: x = 10, y = 20
After swap: x = 20, y = 10


In [ ]:
user = {
    "name": "Alice",
    "age": 30,
    "email": "alice@example.com",
    "is_active": True
}

print(f"{user['name']} is {user['age']} years old.")

Alice is 30 years old.


In [ ]:
words = ["apple", "banana", "apple", "cherry", "banana", "date"]
frequency = {}

for word in words:
    frequency[word] = frequency.get(word, 0) + 1

print(frequency)

{'apple': 2, 'banana': 2, 'cherry': 1, 'date': 1}


In [ ]:
settings = {
    "theme": "dark",
    "font_size": 14,
    "notifications": True
}

if settings["notifications"]:
    print(f"Notifications are enabled. Font size: {settings['font_size']}")

Notifications are enabled. Font size: 14


In [ ]:
import json

json_str = '{"name": "Bob", "age": 25, "city": "New York"}'
data = json.loads(json_str)

print(f"{data['name']} lives in {data['city']}")

Bob lives in New York


In [ ]:
def greet():
    print("Hello!")

def quit_program():
    print("Goodbye!")
    exit()

commands = {
    "hello": greet,
    "quit": quit_program
}

while True:
    cmd = input("Enter a command: ").lower()
    if cmd in commands:
        commands[cmd]()
    else:
        print("Unknown command")

Enter a command: hello
Hello!
Enter a command: greet
Unknown command
Enter a command: quit
Goodbye!


KeyboardInterrupt: Interrupted by user

In [ ]:
# 학생 성적 관리
student_data = {
    "Alice": {
        "scores": [85, 90, 88],    # 리스트를 값으로 사용
        "id": (123, "A")          # 튜플을 값으로 사용
    },
    "Bob": {
        "scores": [78, 82, 79],
        "id": (124, "B")
    },
    "Charlie": {
        "scores": [92, 95, 91],
        "id": (125, "C")
    }
}

# 학생 성적 추가
student_data["Alice"]["scores"].append(95)

# 특정 학생의 데이터 접근
print(student_data["Alice"]["scores"])  # Output: [85, 90, 88, 95]
print(student_data["Alice"]["id"])      # Output: (123, "A")


[85, 90, 88, 95]
(123, 'A')


In [ ]:
text = "hello"

for index, char in enumerate(text):
    print(f"Index: {index}, Character: {char}")


Index: 0, Character: h
Index: 1, Character: e
Index: 2, Character: l
Index: 3, Character: l
Index: 4, Character: o


In [ ]:
fruits = ['apple', 'banana', 'cherry']
fruit_dict = {index: fruit for index, fruit in enumerate(fruits)}

print(fruit_dict)


{0: 'apple', 1: 'banana', 2: 'cherry'}


In [ ]:
fruits = ['apple', 'banana', 'cherry']
indexed_fruits = [(index, fruit) for index, fruit in enumerate(fruits)]

print(indexed_fruits)


[(0, 'apple'), (1, 'banana'), (2, 'cherry')]


In [ ]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits, start=1):
    print(f"Index: {index}, Fruit: {fruit}")


Index: 1, Fruit: apple
Index: 2, Fruit: banana
Index: 3, Fruit: cherry


In [ ]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits):
    print(f"Index: {index}, Fruit: {fruit}")


Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: cherry


In [ ]:
def is_leap_year(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

def get_days_in_month(year, month):
    days_in_month = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if month == 2 and is_leap_year(year):
        return 29
    return days_in_month[month]

def get_first_day_of_month(year, month):
    if month < 3:
        month += 12
        year -= 1
    return (1 + ((13 * (month + 1)) // 5) + year + (year // 4) - (year // 100) + (year // 400)) % 7

def print_calendar(year, month):
    month_names = ["", "January", "February", "March", "April", "May", "June",
                   "July", "August", "September", "October", "November", "December"]

    print(f"{month_names[month]} {year}".center(20))
    print("Mo Tu We Th Fr Sa Su")

    first_day = get_first_day_of_month(year, month)
    days_in_month = get_days_in_month(year, month)

    current_day = 1
    for i in range(6):
        week_str = ""
        for j in range(7):
            if (i == 0 and j < first_day) or current_day > days_in_month:
                week_str += "   "
            else:
                week_str += f"{current_day:2d} "
                current_day += 1
        print(week_str)
        if current_day > days_in_month:
            break

def get_valid_input(prompt, min_value, max_value):
    while True:
        user_input = input(prompt)
        if user_input.isdigit():
            value = int(user_input)
            if min_value <= value <= max_value:
                return value
        print(f"올바른 숫자를 입력하세요 ({min_value}-{max_value}).")

def main():
    year = get_valid_input("연도를 입력하세요 (예: 2024): ", 1, 9999)
    month = get_valid_input("월을 입력하세요 (1-12): ", 1, 12)
    print_calendar(year, month)

if __name__ == "__main__":
    main()

연도를 입력하세요 (예: 2024): 2024
월을 입력하세요 (1-12): 6
     June 2024      
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7 
 8  9 10 11 12 13 14 
15 16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30                


In [ ]:
def decimal_to_binary(decimal_num):
    if decimal_num == 0:
        return "0"
    binary = ""
    while decimal_num > 0:
        binary = str(decimal_num % 2) + binary
        decimal_num //= 2
    return binary

def decimal_to_hex(decimal_num):
    if decimal_num == 0:
        return "0"
    hex_chars = "0123456789ABCDEF"
    hexadecimal = ""
    while decimal_num > 0:
        hexadecimal = hex_chars[decimal_num % 16] + hexadecimal
        decimal_num //= 16
    return hexadecimal

def get_valid_input(prompt):
    while True:
        user_input = input(prompt)
        if user_input.lower() == 'q':
            return None
        if user_input.isdigit():
            return int(user_input)
        print("올바른 숫자를 입력하세요.")

def main():
    while True:
        decimal_input = get_valid_input("10진수를 입력하세요 (종료하려면 'q' 입력): ")
        if decimal_input is None:
            print("프로그램을 종료합니다.")
            break

        binary_result = decimal_to_binary(decimal_input)
        hex_result = decimal_to_hex(decimal_input)

        print(f"10진수: {decimal_input}")
        print(f"2진수: {binary_result}")
        print(f"16진수: {hex_result}")
        print()

if __name__ == "__main__":
    main()

10진수를 입력하세요 (종료하려면 'q' 입력): 100
10진수: 100
2진수: 1100100
16진수: 64

10진수를 입력하세요 (종료하려면 'q' 입력): 50
10진수: 50
2진수: 110010
16진수: 32

10진수를 입력하세요 (종료하려면 'q' 입력): ㅂ
올바른 숫자를 입력하세요.
10진수를 입력하세요 (종료하려면 'q' 입력): q
프로그램을 종료합니다.


In [ ]:
def custom_random(start, end):
    # 간단한 선형 합동 생성기(LCG) 구현
    global seed
    seed = (1103515245 * seed + 12345) & 0x7fffffff
    return start + (seed % (end - start + 1))

def generate_lotto_numbers(theme):
    numbers = []
    if theme == 'adventure':
        while len(numbers) < 6:
            num = custom_random(1, 45)
            if num not in numbers:
                numbers.append(num)
    elif theme == 'fantasy':
        for _ in range(6):
            numbers.append(custom_random(1, 50))
    elif theme == 'sci-fi':
        while len(numbers) < 6:
            num = custom_random(1, 60)
            if num % 2 == 0 and num not in numbers:
                numbers.append(num)
    else:
        return None

    if theme != 'fantasy':
        numbers.sort()
    return numbers

def generate_lotto_tickets(ticket_count, theme):
    return [generate_lotto_numbers(theme) for _ in range(ticket_count)]

def get_valid_input(prompt, valid_options):
    while True:
        user_input = input(prompt)
        if user_input in valid_options:
            return user_input
        print("유효하지 않은 선택입니다. 다시 시도해주세요.")

def get_valid_number(prompt, min_value):
    while True:
        user_input = input(prompt)
        if user_input.isdigit() and int(user_input) >= min_value:
            return int(user_input)
        print(f"{min_value} 이상의 정수를 입력하세요.")

def main():
    global seed
    seed = 12345  # 초기 시드값 설정

    print("로또 테마를 선택하세요:")
    print("1. 모험 (Adventure)")
    print("2. 판타지 (Fantasy)")
    print("3. 과학 판타지 (Sci-Fi)")

    choice = get_valid_input("테마를 선택하세요 (1, 2, 3 중 하나): ", ['1', '2', '3'])
    theme = ['adventure', 'fantasy', 'sci-fi'][int(choice) - 1]

    ticket_count = get_valid_number("생성할 로또 티켓의 수를 입력하세요: ", 1)

    tickets = generate_lotto_tickets(ticket_count, theme)

    print("\n생성된 로또 티켓 번호:")
    for idx, ticket in enumerate(tickets, start=1):
        print(f"티켓 {idx}: {ticket}")

if __name__ == "__main__":
    main()

로또 테마를 선택하세요:
1. 모험 (Adventure)
2. 판타지 (Fantasy)
3. 과학 판타지 (Sci-Fi)
테마를 선택하세요 (1, 2, 3 중 하나): 2
생성할 로또 티켓의 수를 입력하세요: 3

생성된 로또 티켓 번호:
티켓 1: [7, 26, 25, 24, 29, 10]
티켓 2: [43, 44, 11, 18, 45, 48]
티켓 3: [33, 22, 29, 36, 47, 28]
